# Generated by Django 2.1.1 on 2018-10-18 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=16, verbose_name='Kullanıcı Adı')),
                ('sifre', models.CharField(max_length=21, verbose_name='Şifre')),
                ('email', models.EmailField(default='', max_length=51, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='kullanici_ayrinti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(default='', max_length=51, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(default='', max_length=51, null=True, verbose_name='Soysim')),
                ('resim', models.CharField(default='/static/img/default.png', max_length=701, null=True, verbose_name='Resim')),
                ('kayit_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('dogum_tarihi', models.DateTimeField(null=True)),
                ('telefon', models.CharField(blank=True, default='', max_length=11, verbose_name='Telefon No')),
                ('cinsiyet', models.CharField(blank=True, default='', max_length=1)),
                ('kilo', models.IntegerField(default=0)),
                ('boy', models.IntegerField(default=0)),
                ('problem', models.CharField(blank=True, default='', max_length=700)),
                ('pt_kontrol', models.IntegerField(default=0)),
                ('trainer', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
