# Generated by Django 2.1.1 on 2018-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0002_hocalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='uretilen_kodlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField(max_length=5)),
            ],
        ),
    ]
