# Generated by Django 2.1.1 on 2018-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_uretilen_kodlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uretilen_kodlar',
            name='kod',
            field=models.IntegerField(),
        ),
    ]
