# Generated by Django 2.1.1 on 2018-10-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0005_auto_20181019_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocalar',
            name='deneme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kullanicilar.kullanici_ayrinti'),
        ),
    ]
