# Generated by Django 2.1.1 on 2018-10-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0006_hocalar_deneme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocalar',
            name='deneme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kullanicilar.kullanici_ayrinti'),
        ),
    ]
