# Generated by Django 2.1.1 on 2018-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0011_hocalar_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocalar',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Telefon No'),
        ),
    ]
