# Generated by Django 2.1.1 on 2018-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0012_hocalar_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocalar',
            name='cinsiyet',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
