# Generated by Django 2.1.1 on 2018-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0014_okul'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='okul',
            name='bolum',
        ),
    ]
