# Generated by Django 2.1.1 on 2018-10-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0015_auto_20181022_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
