# Generated by Django 2.1.1 on 2018-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0017_auto_20181022_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocalar',
            name='soyisim',
        ),
        migrations.RemoveField(
            model_name='kullanici_ayrinti',
            name='soyisim',
        ),
        migrations.AlterField(
            model_name='hocalar',
            name='isim',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='kullanici_ayrinti',
            name='isim',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='İsim'),
        ),
    ]
