# Generated by Django 2.1.1 on 2018-10-23 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0018_auto_20181023_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='pt_alan_ogrenciler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.IntegerField(default=0, null=True, verbose_name='aldığı saat')),
                ('paket', models.CharField(default='', max_length=50, null=True, verbose_name='Alınan Paket')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kullanicilar.hocalar', verbose_name='Eğitmen')),
                ('isim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kullanicilar.kullanici_ayrinti', verbose_name='isim')),
                ('ogr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogr_id', to='kullanicilar.kullanici_ayrinti')),
            ],
        ),
    ]
