# Generated by Django 2.1.1 on 2018-10-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0019_pt_alan_ogrenciler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_alan_ogrenciler',
            name='ogr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kullanicilar.kullanici'),
        ),
    ]
