# Generated by Django 2.1.1 on 2018-10-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0021_auto_20181023_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_alan_ogrenciler',
            name='ogr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_id', to='kullanicilar.kullanici'),
        ),
    ]
