# Generated by Django 2.1.1 on 2018-10-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0023_remove_hocalar_deneme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_alan_ogrenciler',
            name='ogr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kullanicilar.kullanici'),
        ),
    ]
